type StyleTypes = {
  avatarStyle: Array<string>;
  topType: Array<string>;
  accessoriesType: Array<string>;
  hairColor: Array<string>;
  facialHairType: Array<string>;
  clotheType: Array<string>;
  eyeType: Array<string>;
  eyebrowType: Array<string>;
  mouthType: Array<string>;
  skinColor: Array<string>;
};

export const options: StyleTypes = {
  avatarStyle: [
    "Transparent",
    //   "Circle"
  ],
  topType: [
    // "NoHair",
    // "Eyepatch",
    "Hat",
    "Hijab",
    // "Turban",
    "WinterHat1",
    "WinterHat2",
    "WinterHat3",
    "WinterHat4",
    "LongHairBigHair",
    "LongHairBob",
    "LongHairBun",
    "LongHairCurly",
    "LongHairCurvy",
    "LongHairDreads",
    "LongHairFrida",
    "LongHairFro",
    "LongHairFroBand",
    "LongHairNotTooLong",
    "LongHairShavedSides",
    "LongHairMiaWallace",
    "LongHairStraight",
    "LongHairStraight2",
    "LongHairStraightStrand",
    "ShortHairDreads01",
    "ShortHairDreads02",
    "ShortHairFrizzle",
    "ShortHairShaggyMullet",
    "ShortHairShortCurly",
    "ShortHairShortFlat",
    "ShortHairShortRound",
    "ShortHairShortWaved",
    "ShortHairSides",
    "ShortHairTheCaesar",
    "ShortHairTheCaesarSidePart",
  ],
  accessoriesType: [
    "Blank",
    // "Kurt",
    "Prescription01",
    "Prescription02",
    "Round",
    // "Sunglasses",
    // "Wayfarers",
  ],
  hairColor: [
    "Auburn",
    "Black",
    "Blonde",
    "BlondeGolden",
    "Brown",
    "BrownDark",
    "PastelPink",
    "Blue",
    "Platinum",
    "Red",
    "SilverGray",
  ],
  facialHairType: [
    "Blank",
    // "BeardMedium",
    // "BeardLight",
    // "BeardMajestic",
    // "MoustacheFancy",
    // "MoustacheMagnum",
  ],
  clotheType: [
    "BlazerShirt",
    "BlazerSweater",
    "CollarSweater",
    "GraphicShirt",
    "Hoodie",
    "Overall",
    "ShirtCrewNeck",
    "ShirtScoopNeck",
    "ShirtVNeck",
  ],
  eyeType: [
    // "Close",
    // "Cry",
    "Default",
    // "Dizzy",
    // "EyeRoll",
    "Happy",
    // "Hearts",
    // "Side",
    // "Squint",
    // "Surprised",
    // "Wink",
    // "WinkWacky",
    // "Angry",
    // "AngryNatural",
  ],
  eyebrowType: [
    "Default",
    "DefaultNatural",
    "FlatNatural",
    "RaisedExcited",
    "RaisedExcitedNatural",
    // "SadConcerned",
    // "SadConcernedNatural",
    // "UnibrowNatural",
    // "UpDown",
    // "UpDownNatural",
    // "Concerned",
  ],
  mouthType: [
    "Default",
    // "Disbelief",
    // "Eating",
    // "Grimace",
    // "Sad",
    // "ScreamOpen",
    // "Serious",
    "Smile",
    // "Tongue",
    // "Twinkle",
    // "Vomit",
  ],
  skinColor: [
    "Tanned",
    "Yellow",
    "Pale",
    "Light",
    "Brown",
    "DarkBrown",
    "Black",
  ],
};
